export const itemsOccasion = [
  { value: 'Baby Shower', label: 'Baby Shower' },
  { value: 'Baptism', label: 'Baptism' },
  { value: 'Bachelorette Party', label: 'Bachelorette Party' },
  { value: 'Bar Mitzvah', label: 'Bar Mitzvah' },
  { value: 'Bat Mitzvah', label: 'Bat Mitzvah' },
  { value: 'Birthday', label: 'Birthday' },
  { value: 'Bridal Shower', label: 'Bridal Shower' },
  { value: 'Childbirth', label: 'Childbirth' },
  { value: 'Chinese New Year', label: 'Chinese New Year' },
  { value: 'Christening', label: 'Christening' },
  { value: 'Christmas', label: 'Christmas' },
  { value: 'Diwali', label: 'Diwali' },
  { value: 'Easter', label: 'Easter' },
  { value: 'Eid', label: 'Eid' },
  { value: 'Engagement Party', label: 'Engagement Party' },
  { value: 'Father’s Day', label: 'Father’s Day' },
  { value: 'First Day Of School', label: 'First Day Of School' },
  { value: 'Fourth Of July', label: 'Fourth Of July' },
  { value: 'Friendship', label: 'Friendship' },
  { value: 'Gender Reveal', label: 'Gender Reveal' },
  { value: 'Graduation', label: 'Graduation' },
  { value: 'Halloween', label: 'Halloween' },
  { value: 'Hanukkah', label: 'Hanukkah' },
  { value: 'Housewarming', label: 'Housewarming' },
  { value: 'Labor Day', label: 'Labor Day' },
  { value: 'Mother’s Day', label: 'Mother’s Day' },
  { value: 'New Years', label: 'New Years' },
  { value: 'Parting Gift', label: 'Parting Gift' },
  { value: 'Promotion', label: 'Promotion' },
  { value: 'Religious Occasion', label: 'Religious Occasion' },
  { value: 'Retirement', label: 'Retirement' },
  { value: 'Sip And See Party', label: 'Sip And See Party' },
  { value: 'Surprise Gift', label: 'Surprise Gift' },
  { value: 'Valentine’s Day', label: 'Valentine’s Day' },
  { value: 'Wedding', label: 'Wedding' },
  { value: 'Wedding Anniversary', label: 'Wedding Anniversary' },
  { value: 'Wedding Reception', label: 'Wedding Reception' },
];

export const itemsAge = [
  { value: 'Infant', label: 'Infant' },
  { value: 'Toddler', label: 'Toddler' },
  { value: ' Small Child', label: 'Small Child' },
  { value: 'Pre-Teen', label: 'Pre-Teen' },
  { value: 'Teenager', label: 'Teenager' },
  { value: ' Adult', label: 'Adult' },
  { value: ' Senior', label: 'Senior' },
];
export const itemsSex = [
  { value: 'Male', label: 'Male' },
  { value: 'Female', label: 'Female' },
];

export const itemsFamily = [
  { value: 'Single', label: 'Single' },
  { value: 'Married', label: 'Married' },
  { value: 'Children', label: 'Children' },
  { value: 'Cat', label: 'Cat' },
  { value: 'Dog', label: 'Dog' },
];

export const itemsNationality = [
  { value: 'Afghan', label: 'Afghan' },
  { value: 'Albanian', label: 'Albanian' },
  { value: 'Algerian', label: 'Algerian' },
  { value: 'American', label: 'American' },
  { value: 'Andorran', label: 'Andorran' },
  { value: 'Angolan', label: 'Angolan' },
  { value: 'Antiguans', label: 'Antiguans' },
  { value: 'Argentinean', label: 'Argentinean' },
  { value: 'Armenian', label: 'Armenian' },
  { value: 'Australian', label: 'Australian' },
  { value: 'Austrian', label: 'Austrian' },
  { value: 'Azerbaijani', label: 'Azerbaijani' },
  { value: 'Bahamian', label: 'Bahamian' },
  { value: 'Bahraini', label: 'Bahraini' },
  { value: 'Bangladeshi', label: 'Bangladeshi' },
  { value: 'Barbadian', label: 'Barbadian' },
  { value: 'Barbudans', label: 'Barbudans' },
  { value: 'Batswana', label: 'Batswana' },
  { value: 'Belarusian', label: 'Belarusian' },
  { value: 'Belgian', label: 'Belgian' },
  { value: 'Belizean', label: 'Belizean' },
  { value: 'Beninese', label: 'Beninese' },
  { value: 'Bhutanese', label: 'Bhutanese' },
  { value: 'Bolivian', label: 'Bolivian' },
  { value: 'Bosnian', label: 'Bosnian' },
  { value: 'Brazilian', label: 'Brazilian' },
  { value: 'British', label: 'British' },
  { value: 'Bruneian', label: 'Bruneian' },
  { value: 'Bulgarian', label: 'Bulgarian' },
  { value: 'Burkinabe', label: 'Burkinabe' },
  { value: 'Burmese', label: 'Burmese' },
  { value: 'Burundian', label: 'Burundian' },
  { value: 'Cambodian', label: 'Cambodian' },
  { value: 'Cameroonian', label: 'Cameroonian' },
  { value: 'Canadian', label: 'Canadian' },
  { value: 'Cape Verdean', label: 'Cape Verdean' },
  { value: 'Central African', label: 'Central African' },
  { value: 'Chadian', label: 'Chadian' },
  { value: 'Chilean', label: 'Chilean' },
  { value: 'Chinese', label: 'Chinese' },
  { value: 'Colombian', label: 'Colombian' },
  { value: 'Comoran', label: 'Comoran' },
  { value: 'Congolese', label: 'Congolese' },
  { value: 'Costa Rican', label: 'Costa Rican' },
  { value: 'Croatian', label: 'Croatian' },
  { value: 'Cuban', label: 'Cuban' },
  { value: 'Cypriot', label: 'Cypriot' },
  { value: 'Czech', label: 'Czech' },
  { value: 'Danish', label: 'Danish' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominican', label: 'Dominican' },
  { value: 'Dutch', label: 'Dutch' },
  { value: 'East Timorese', label: 'East Timorese' },
  { value: 'Ecuadorean', label: 'Ecuadorean' },
  { value: 'Egyptian', label: 'Egyptian' },
  { value: 'Emirian', label: 'Emirian' },
  { value: 'Equatorial Guinean', label: 'Equatorial Guinean' },
  { value: 'Eritrean', label: 'Eritrean' },
  { value: 'Estonian', label: 'Estonian' },
  { value: 'Ethiopian', label: 'Ethiopian' },
  { value: 'Fijian', label: 'Fijian' },
  { value: 'Filipino', label: 'Filipino' },
  { value: 'Finnish', label: 'Finnish' },
  { value: 'French', label: 'French' },
  { value: 'Gabonese', label: 'Gabonese' },
  { value: 'Gambian', label: 'Gambian' },
  { value: 'Georgian', label: 'Georgian' },
  { value: 'German', label: 'German' },
  { value: 'Ghanaian', label: 'Ghanaian' },
  { value: 'Greek', label: 'Greek' },
  { value: 'Grenadian', label: 'Grenadian' },
  { value: 'Guatemalan', label: 'Guatemalan' },
  { value: 'Guinea-Bissauan', label: 'Guinea-Bissauan' },
  { value: 'Guinean', label: 'Guinean' },
  { value: 'Guyanese', label: 'Guyanese' },
  { value: 'Haitian', label: 'Haitian' },
  { value: 'Herzegovinian', label: 'Herzegovinian' },
  { value: 'Honduran', label: 'Honduran' },
  { value: 'Hungarian', label: 'Hungarian' },
  { value: 'I-Kiribati', label: 'I-Kiribati' },
  { value: 'Icelander', label: 'Icelander' },
  { value: 'Indian', label: 'Indian' },
  { value: 'Indonesian', label: 'Indonesian' },
  { value: 'Iranian', label: 'Iranian' },
  { value: 'Iraqi', label: 'Iraqi' },
  { value: 'Irish', label: 'Irish' },
  { value: 'Israeli', label: 'Israeli' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Ivorian', label: 'Ivorian' },
  { value: 'Jamaican', label: 'Jamaican' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Jordanian', label: 'Jordanian' },
  { value: 'Kazakhstani', label: 'Kazakhstani' },
  { value: 'Kenyan', label: 'Kenyan' },
  { value: 'Kittian and Nevisian', label: 'Kittian and Nevisian' },
  { value: 'Kuwaiti', label: 'Kuwaiti' },
  { value: 'Kyrgyz', label: 'Kyrgyz' },
  { value: 'Laotian', label: 'Laotian' },
  { value: 'Latvian', label: 'Latvian' },
  { value: 'Lebanese', label: 'Lebanese' },
  { value: 'Liberian', label: 'Liberian' },
  { value: 'Libyan', label: 'Libyan' },
  { value: 'Liechtensteiner', label: 'Liechtensteiner' },
  { value: 'Lithuanian', label: 'Lithuanian' },
  { value: 'Luxembourger', label: 'Luxembourger' },
  { value: 'Macedonian', label: 'Macedonian' },
  { value: 'Malagasy', label: 'Malagasy' },
  { value: 'Malawian', label: 'Malawian' },
  { value: 'Malaysian', label: 'Malaysian' },
  { value: 'Maldivian', label: 'Maldivian' },
  { value: 'Malian', label: 'Malian' },
  { value: 'Maltese', label: 'Maltese' },
  { value: 'Marshallese', label: 'Marshallese' },
  { value: 'Mauritanian', label: 'Mauritanian' },
  { value: 'Mauritian', label: 'Mauritian' },
  { value: 'Mexican', label: 'Mexican' },
  { value: 'Micronesian', label: 'Micronesian' },
  { value: 'Moldovan', label: 'Moldovan' },
  { value: 'Monacan', label: 'Monacan' },
  { value: 'Mongolian', label: 'Mongolian' },
  { value: 'Moroccan', label: 'Moroccan' },
  { value: 'Mosotho', label: 'Mosotho' },
  { value: 'Motswana', label: 'Motswana' },
  { value: 'Mozambican', label: 'Mozambican' },
  { value: 'Namibian', label: 'Namibian' },
  { value: 'Nauruan', label: 'Nauruan' },
  { value: 'Nepalese', label: 'Nepalese' },
  { value: 'New Zealander', label: 'New Zealander' },
  { value: 'Ni-Vanuatu', label: 'Ni-Vanuatu' },
  { value: 'Nicaraguan', label: 'Nicaraguan' },
  { value: 'Nigerian', label: 'Nigerian' },
  { value: 'Nigerien', label: 'Nigerien' },
  { value: 'North Korean', label: 'North Korean' },
  { value: 'Northern Irish', label: 'Northern Irish' },
  { value: 'Norwegian', label: 'Norwegian' },
  { value: 'Omani', label: 'Omani' },
  { value: 'Pakistani', label: 'Pakistani' },
  { value: 'Palauan', label: 'Palauan' },
  { value: 'Panamanian', label: 'Panamanian' },
  { value: 'Papua New Guinean', label: 'Papua New Guinean' },
  { value: 'Paraguayan', label: 'Paraguayan' },
  { value: 'Peruvian', label: 'Peruvian' },
  { value: 'Polish', label: 'Polish' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Qatari', label: 'Qatari' },
  { value: 'Romanian', label: 'Romanian' },
  { value: 'Russian', label: 'Russian' },
  { value: 'Rwandan', label: 'Rwandan' },
  { value: 'Saint Lucian', label: 'Saint Lucian' },
  { value: 'Salvadoran', label: 'Salvadoran' },
  { value: 'Samoan', label: 'Samoan' },
  { value: 'San Marinese', label: 'San Marinese' },
  { value: 'Sao Tomean', label: 'Sao Tomean' },
  { value: 'Saudi', label: 'Saudi' },
  { value: 'Scottish', label: 'Scottish' },
  { value: 'Senegalese', label: 'Senegalese' },
  { value: 'Serbian', label: 'Serbian' },
  { value: 'Seychellois', label: 'Seychellois' },
  { value: 'Sierra Leonean', label: 'Sierra Leonean' },
  { value: 'Singaporean', label: 'Singaporean' },
  { value: 'Slovakian', label: 'Slovakian' },
  { value: 'Slovenian', label: 'Slovenian' },
  { value: 'Solomon Islander', label: 'Solomon Islander' },
  { value: 'Somali', label: 'Somali' },
  { value: 'South African', label: 'South African' },
  { value: 'South Korean', label: 'South Korean' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'Sri Lankan', label: 'Sri Lankan' },
  { value: 'Sudanese', label: 'Sudanese' },
  { value: 'Surinamer', label: 'Surinamer' },
  { value: 'Swazi', label: 'Swazi' },
  { value: 'Swedish', label: 'Swedish' },
  { value: 'Swiss', label: 'Swiss' },
  { value: 'Syrian', label: 'Syrian' },
  { value: 'Taiwanese', label: 'Taiwanese' },
  { value: 'Tajik', label: 'Tajik' },
  { value: 'Tanzanian', label: 'Tanzanian' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Togolese', label: 'Togolese' },
  { value: 'Tongan', label: 'Tongan' },
  { value: 'Trinidadian or Tobagonian', label: 'Trinidadian or Tobagonian' },
  { value: 'Tunisian', label: 'Tunisian' },
  { value: 'Turkish', label: 'Turkish' },
  { value: 'Tuvaluan', label: 'Tuvaluan' },
  { value: 'Ugandan', label: 'Ugandan' },
  { value: 'Ukrainian', label: 'Ukrainian' },
  { value: 'Uruguayan', label: 'Uruguayan' },
  { value: 'Uzbekistani', label: 'Uzbekistani' },
  { value: 'Venezuelan', label: 'Venezuelan' },
  { value: 'Vietnamese', label: 'Vietnamese' },
  { value: 'Welsh', label: 'Welsh' },
  { value: 'Yemenite', label: 'Yemenite' },
  { value: 'Zambian', label: 'Zambian' },
  { value: 'Zimbabwean', label: 'Zimbabwean' },
];

export const itemsReligion = [
  { value: 'Atheism/Agnosticism', label: 'Atheism/Agnosticism' },
  { value: 'African Diaspora', label: 'African Diaspora' },
  { value: 'Bahá’í', label: 'Bahá’í' },
  { value: 'Buddhism', label: 'Buddhism' },
  { value: 'Christianity', label: 'Christianity' },
  { value: 'Confucianism', label: 'Confucianism' },
  { value: 'Druze', label: 'Druze' },
  { value: 'Gnosticism', label: 'Gnosticism' },
  { value: 'Hinduism', label: 'Hinduism' },
  { value: 'Indigenous American', label: 'Indigenous American' },
  { value: 'Islam', label: 'Islam' },
  { value: 'Jainism', label: 'Jainism' },
  { value: 'Judaism', label: 'Judaism' },
  { value: 'Rastafarianism', label: 'Rastafarianism' },
  { value: 'Shinto', label: 'Shinto' },
  { value: 'Sikhism', label: 'Sikhism' },
  { value: 'Traditional African', label: 'Traditional African' },
  { value: 'Zoroastrianism', label: 'Zoroastrianism' },
];

export const itemsOccupations = [
  { value: 'White Collar', label: 'White Collar' },
  { value: 'Blue Collar', label: 'Blue Collar' },
  { value: 'No Collar', label: 'No Collar' },
  { value: 'Accountant', label: 'Accountant' },
  { value: 'Actor', label: 'Actor' },
  { value: 'Ambassador', label: 'Ambassador' },
  { value: 'Animator', label: 'Animator' },
  { value: 'Architect', label: 'Architect' },
  { value: 'Artist', label: 'Artist' },
  { value: 'Astronomer', label: 'Astronomer' },
  { value: 'Athlete', label: 'Athlete' },
  { value: 'Attorney', label: 'Attorney' },
  { value: 'Author', label: 'Author' },
  { value: 'Babysitter', label: 'Babysitter' },
  { value: 'Baker', label: 'Baker' },
  { value: 'Banker', label: 'Banker' },
  { value: 'Barber', label: 'Barber' },
  { value: 'Bartender', label: 'Bartender' },
  { value: 'Biologist', label: 'Biologist' },
  { value: 'Butcher', label: 'Butcher' },
  { value: 'Calligrapher', label: 'Calligrapher' },
  { value: 'Captain', label: 'Captain' },
  { value: 'Caregiver', label: 'Caregiver' },
  { value: 'Carpenter', label: 'Carpenter' },
  { value: 'Chef', label: 'Chef' },
  { value: 'Chemist', label: 'Chemist' },
  { value: 'Civil Servant', label: 'Civil Servant' },
  { value: 'Clerk', label: 'Clerk' },
  { value: 'Coach', label: 'Coach' },
  { value: 'Comedian', label: 'Comedian' },
  { value: 'Composer', label: 'Composer' },
  { value: 'Counselor', label: 'Counselor' },
  { value: 'Cryptographer', label: 'Cryptographer' },
  { value: 'Custodian', label: 'Custodian' },
  { value: 'Dancer', label: 'Dancer' },
  { value: 'Dentist', label: 'Dentist' },
  { value: 'Deputy', label: 'Deputy' },
  { value: 'Designer', label: 'Designer' },
  { value: 'Doctor', label: 'Doctor' },
  { value: 'Ecologist', label: 'Ecologist' },
  { value: 'Economist', label: 'Economist' },
  { value: 'Editor', label: 'Editor' },
  { value: 'Electrician', label: 'Electrician' },
  { value: 'Engineer', label: 'Engineer' },
  { value: 'Entertainer', label: 'Entertainer' },
  { value: 'Farmer', label: 'Farmer' },
  { value: 'Filmmaker', label: 'Filmmaker' },
  { value: 'Firefighter', label: 'Firefighter' },
  { value: 'Florist', label: 'Florist' },
  { value: 'Gardener', label: 'Gardener' },
  { value: 'Governor', label: 'Governor' },
  { value: 'Guitarist', label: 'Guitarist' },
  { value: 'Hairdresser', label: 'Hairdresser' },
  { value: 'Housekeeper', label: 'Housekeeper' },
  { value: 'Housewife', label: 'Housewife' },
  { value: 'Hunter', label: 'Hunter' },
  { value: 'Illustrator', label: 'Illustrator' },
  { value: 'Instructor', label: 'Instructor' },
  { value: 'Inventor', label: 'Inventor' },
  { value: 'Janitor', label: 'Janitor' },
  { value: 'Journalist', label: 'Journalist' },
  { value: 'Judge', label: 'Judge' },
  { value: 'Laborer', label: 'Laborer' },
  { value: 'Landlord', label: 'Landlord' },
  { value: 'Lawyer', label: 'Lawyer' },
  { value: 'Magician', label: 'Magician' },
  { value: 'Manager', label: 'Manager' },
  { value: 'Manga artist', label: 'Manga artist' },
  { value: 'Mayor', label: 'Mayor' },
  { value: 'Mechanic', label: 'Mechanic' },
  { value: 'Medical', label: 'Medical' },
  { value: 'Midwife', label: 'Midwife' },
  { value: 'Military', label: 'Military' },
  { value: 'Model', label: 'Model' },
  { value: 'Musician', label: 'Musician' },
  { value: 'Nurse', label: 'Nurse' },
  { value: 'Nutritionist', label: 'Nutritionist' },
  { value: 'Office worker', label: 'Office worker' },
  { value: 'Officer', label: 'Officer' },
  { value: 'Operator', label: 'Operator' },
  { value: 'Painter', label: 'Painter' },
  { value: 'Paramedic', label: 'Paramedic' },
  { value: 'Percussionist', label: 'Percussionist' },
  { value: 'Performer', label: 'Performer' },
  { value: 'Photographer', label: 'Photographer' },
  { value: 'Physician', label: 'Physician' },
  { value: 'Pianist', label: 'Pianist' },
  { value: 'Pilot', label: 'Pilot' },
  { value: 'Pitcher', label: 'Pitcher' },
  { value: 'Plumber', label: 'Plumber' },
  { value: 'Poet', label: 'Poet' },
  { value: 'Police', label: 'Police' },
  { value: 'Politician', label: 'Politician' },
  { value: 'Producer', label: 'Producer' },
  { value: 'Professor', label: 'Professor' },
  { value: 'Programmer', label: 'Programmer' },
  { value: 'Psychologist', label: 'Psychologist' },
  { value: 'Publisher', label: 'Publisher' },
  { value: 'Rancher', label: 'Rancher' },
  { value: 'Ranger', label: 'Ranger' },
  { value: 'Real estate agent', label: 'Real estate a' },
  { value: 'Retailer', label: 'Retailer' },
  { value: 'Retiree', label: 'Retiree' },
  { value: 'Ride Share Driver', label: 'Ride Share Dr' },
  { value: 'Sailor', label: 'Sailor' },
  { value: 'Salesperson', label: 'Salesperson' },
  { value: 'Scholar', label: 'Scholar' },
  { value: 'Scientist', label: 'Scientist' },
  { value: 'Seamstress', label: 'Seamstress' },
  { value: 'Senator', label: 'Senator' },
  { value: 'Sheriff', label: 'Sheriff' },
  { value: 'Singer', label: 'Singer' },
  { value: 'Smith', label: 'Smith' },
  { value: 'Student', label: 'Student' },
  { value: 'Surgeon', label: 'Surgeon' },
  { value: 'Tailor', label: 'Tailor' },
  { value: 'Teacher', label: 'Teacher' },
  { value: 'Technician', label: 'Technician' },
  { value: 'Therapist', label: 'Therapist' },
  { value: 'Trainer', label: 'Trainer' },
  { value: 'Truck driver', label: 'Truck driver' },
  { value: 'Tutor', label: 'Tutor' },
  { value: 'Valet', label: 'Valet' },
  { value: 'Veteran', label: 'Veteran' },
  { value: 'Veterinarian', label: 'Veterinarian' },
  { value: 'Waiter', label: 'Waiter' },
  { value: 'Waitress', label: 'Waitress' },
  { value: 'Warden', label: 'Warden' },
  { value: 'Welder', label: 'Welder' },
  { value: 'Woodcarver', label: 'Woodcarver' },
  { value: 'Zookeeper', label: 'Zookeeper' },
];

export const itemsPersonality = [
  { value: 'Academic', label: 'Academic' },
  { value: 'Active', label: 'Active' },
  { value: 'Adventurous', label: 'Adventurous' },
  { value: 'Adrenaline Junkie', label: 'Adrenaline Junkie' },
  { value: 'Animal Lover', label: 'Animal Lover' },
  { value: 'Artistic', label: 'Artistic' },
  { value: 'Athletic', label: 'Athletic' },
  { value: 'Avante Garde', label: 'Avante Garde' },
  { value: 'Bookworm', label: 'Bookworm' },
  { value: 'Botanist', label: 'Botanist' },
  { value: 'Calm', label: 'Calm' },
  { value: 'Childish', label: 'Childish' },
  { value: 'Clever', label: 'Clever' },
  { value: 'Couchpotato', label: 'Couchpotato' },
  { value: 'Diva', label: 'Diva' },
  { value: 'Eccentric', label: 'Eccentric' },
  { value: 'Eco-Friendly', label: 'Eco-Friendly' },
  { value: 'Equestrian', label: 'Equestrian' },
  { value: 'Estudious', label: 'Estudious' },
  { value: 'Exciting', label: 'Exciting' },
  { value: 'Explorer', label: 'Explorer' },
  { value: 'Family Oriented', label: 'Family Oriented' },
  { value: 'Flirty', label: 'Flirty' },
  { value: 'Foodie', label: 'Foodie' },
  { value: 'Frugal', label: 'Frugal' },
  { value: 'Gamer', label: 'Gamer' },
  { value: 'Green Thumb', label: 'Green Thumb' },
  { value: 'Handy', label: 'Handy' },
  { value: 'Hands-On', label: 'Hands-On' },
  { value: 'Homebody', label: 'Homebody' },
  { value: 'Hydrophile', label: 'Hydrophile' },
  { value: 'Intellectual', label: 'Intellectual' },
  { value: 'Minimalist', label: 'Minimalist' },
  { value: 'Music-Lover', label: 'Music-Lover' },
  { value: 'Musician', label: 'Musician' },
  { value: 'Nature-Lover', label: 'Nature-Lover' },
  { value: 'Organized', label: 'Organized' },
  { value: 'Patriotic', label: 'Patriotic' },
  { value: 'Playful', label: 'Playful' },
  { value: 'Pleasant', label: 'Pleasant' },
  { value: 'Political', label: 'Political' },
  { value: 'Practical Joker', label: 'Practical Joker' },
  { value: 'Professional', label: 'Professional' },
  { value: 'Religious', label: 'Religious' },
  { value: 'Retired', label: 'Retired' },
  { value: 'Romantic', label: 'Romantic' },
  { value: 'Sense Of Humor', label: 'Sense Of Humor' },
  { value: 'Sensual', label: 'Sensual' },
  { value: 'Sightseer', label: 'Sightseer' },
  { value: 'Space Cadet', label: 'Space Cadet' },
  { value: 'Stoner', label: 'Stoner' },
  { value: 'Techie', label: 'Techie' },
  { value: 'Traveler', label: 'Traveler' },
  { value: 'Thrill Seeker', label: 'Thrill Seeker' },
  { value: 'Vegetarian', label: 'Vegetarian' },
  { value: 'Whimsical', label: 'Whimsical' },
  { value: 'Witty', label: 'Witty' },
  { value: 'Workaholic', label: 'Workaholic' },
];

export const mainCategories = [
  { value: 'Art', label: 'Art' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Music', label: 'Music' },
  { value: 'Film', label: 'Film' },
  { value: 'Video Games', label: 'Video Games' },
  { value: 'Outdoor Hobbies', label: 'Outdoor Hobbies' },
  { value: 'Indoor Hobbies', label: 'Indoor Hobbies' },
  { value: 'Favourite Animals', label: 'Favourite Animals' },
  { value: 'Supernatural', label: 'Supernatural' },
  { value: 'Toys', label: 'Toys' },
];

export const subCategories = {
  Art: [
    { value: 'Abstract', label: 'Abstract' },
    { value: 'Architecture', label: 'Architecture' },
    { value: 'Body', label: 'Body' },
    { value: 'Carving', label: 'Carving' },
    { value: 'Cinema', label: 'Cinema' },
    { value: 'Crafts', label: 'Crafts' },
    { value: 'Digital', label: 'Digital' },
    { value: 'Drawing', label: 'Drawing' },
    { value: 'Impressionism', label: 'Impressionism' },
    { value: 'Painting', label: 'Painting' },
    { value: 'Performing', label: 'Performing' },
    { value: 'Sculpting', label: 'Sculpting' },
    { value: 'Sketching', label: 'Sketching' },
    { value: 'Surrealist', label: 'Surrealist' },
  ],
  Sports: [
    { value: 'Archery', label: 'Archery' },
    { value: 'Arm Wrestling', label: 'Arm Wrestling' },
    { value: 'Athletics', label: 'Athletics' },
    { value: 'Badminton', label: 'Badminton' },
    { value: 'Baseball', label: 'Baseball' },
    { value: 'Basketball', label: 'Basketball' },
    { value: 'Billiards', label: 'Billiards' },
    { value: 'Bmx', label: 'Bmx' },
    { value: 'Bowling', label: 'Bowling' },
    { value: 'Boxing', label: 'Boxing' },
    { value: 'Bullriding', label: 'Bullriding' },
    { value: 'Canoeing', label: 'Canoeing' },
    { value: 'Cheerleading', label: 'Cheerleading' },
    { value: 'Climbing', label: 'Climbing' },
    { value: 'Competitive Dancing', label: 'Competitive Dancing' },
    { value: 'Cricket', label: 'Cricket' },
    { value: 'Cue', label: 'Cue' },
    { value: 'Cycling', label: 'Cycling' },
    { value: 'Diving', label: 'Diving' },
    { value: 'Dodgeball', label: 'Dodgeball' },
    { value: 'Esports', label: 'Esports' },
    { value: 'Fencing', label: 'Fencing' },
    { value: 'Field Hockey', label: 'Field Hockey' },
    { value: 'Fishing', label: 'Fishing' },
    { value: 'Football', label: 'Football' },
    { value: 'Freerunning', label: 'Freerunning' },
    { value: 'Frisbee', label: 'Frisbee' },
    { value: 'Gliding', label: 'Gliding' },
    { value: 'Golf', label: 'Golf' },
    { value: 'Grappling', label: 'Grappling' },
    { value: 'Gymnastics', label: 'Gymnastics' },
    { value: 'Handball', label: 'Handball' },
    { value: 'Hiking', label: 'Hiking' },
    { value: 'Hunting', label: 'Hunting' },
    { value: 'Ice Hockey', label: 'Ice Hockey' },
    { value: 'Kayaking', label: 'Kayaking' },
    { value: 'Kite', label: 'Kite' },
    { value: 'Martial Arts', label: 'Martial Arts' },
    { value: 'Mma', label: 'Mma' },
    { value: 'Motorboat Racing', label: 'Motorboat Racing' },
    { value: 'Netball', label: 'Netball' },
    { value: 'Parachuting', label: 'Parachuting' },
    { value: 'Parkour', label: 'Parkour' },
    { value: 'Pole', label: 'Pole' },
    { value: 'Racket', label: 'Racket' },
    { value: 'Rafting', label: 'Rafting' },
    { value: 'Rc Racing', label: 'Rc Racing' },
    { value: 'Robot Combat', label: 'Robot Combat' },
    { value: 'Rodeo', label: 'Rodeo' },
    { value: 'Rollerblading', label: 'Rollerblading' },
    { value: 'Rowing', label: 'Rowing' },
    { value: 'Rowing', label: 'Rowing' },
    { value: 'Rugby', label: 'Rugby' },
    { value: 'Sailing', label: 'Sailing' },
    { value: 'Scootering', label: 'Scootering' },
    { value: 'Shooting', label: 'Shooting' },
    { value: 'Skateboarding', label: 'Skateboarding' },
    { value: 'Skating', label: 'Skating' },
    { value: 'Skimboarding', label: 'Skimboarding' },
    { value: 'Sledding', label: 'Sledding' },
    { value: 'Snowboarding', label: 'Snowboarding' },
    { value: 'Striking', label: 'Striking' },
    { value: 'Stunt', label: 'Stunt' },
    { value: 'Surfing', label: 'Surfing' },
    { value: 'Swimming', label: 'Swimming' },
    { value: 'Table Tennis', label: 'Table Tennis' },
    { value: 'Tennis', label: 'Tennis' },
    { value: 'Trampolining', label: 'Trampolining' },
    { value: 'Unicycling', label: 'Unicycling' },
    { value: 'Volleyball', label: 'Volleyball' },
    { value: 'Volleyball', label: 'Volleyball' },
    { value: 'Water Polo', label: 'Water Polo' },
    { value: 'Weapon', label: 'Weapon' },
    { value: 'Weightlifting', label: 'Weightlifting' },
    { value: 'Wiffleball', label: 'Wiffleball' },
    { value: 'Winter Guard', label: 'Winter Guard' },
    { value: 'Wrestling   ', label: 'Wrestling' },
  ],
  Music: [
    { value: 'Acoustic', label: 'Acoustic' },
    { value: 'Acapella', label: 'Acapella' },
    { value: 'Alternative', label: 'Alternative' },
    { value: 'Anime', label: 'Anime' },
    { value: 'Blues', label: 'Blues' },
    { value: 'Bachata', label: 'Bachata' },
    { value: 'Childrens Music', label: 'Childrens Music' },
    { value: 'Classic Rock', label: 'Classic Rock' },
    { value: 'Comedy', label: 'Comedy' },
    { value: 'Commercial', label: 'Commercial' },
    { value: 'Country', label: 'Country' },
    { value: 'Dance', label: 'Dance' },
    { value: 'Disney', label: 'Disney' },
    { value: 'Dubstep', label: 'Dubstep' },
    { value: 'Easy Listening', label: 'Easy Listening' },
    { value: 'Electronic', label: 'Electronic' },
    { value: 'Edm', label: 'Edm' },
    { value: 'Emo', label: 'Emo' },
    { value: 'Fitness & Workout', label: 'Fitness & Workout' },
    { value: 'French Pop', label: 'French Pop' },
    { value: 'Folk Music', label: 'Folk Music' },
    { value: 'German Folk', label: 'German Folk' },
    { value: 'Goth', label: 'Goth' },
    { value: 'Hard Rock', label: 'Hard Rock' },
    { value: 'Hip Hop', label: 'Hip Hop' },
    { value: 'Holiday', label: 'Holiday' },
    { value: 'Indie Pop', label: 'Indie Pop' },
    { value: 'Industrial', label: 'Industrial' },
    { value: 'Inspirational', label: 'Inspirational' },
    { value: 'Instrumental', label: 'Instrumental' },
    { value: 'J-Pop', label: 'J-Pop' },
    { value: 'Jazz', label: 'Jazz' },
    { value: 'K-Pop', label: 'K-Pop' },
    { value: 'Karaoke', label: 'Karaoke' },
    { value: 'Kayokyoku', label: 'Kayokyoku' },
    { value: 'Latin', label: 'Latin' },
    { value: 'Merengue', label: 'Merengue' },
    { value: 'Metal', label: 'Metal' },
    { value: 'New Age', label: 'New Age' },
    { value: 'New Wave', label: 'New Wave' },
    { value: 'Opera', label: 'Opera' },
    { value: 'Party', label: 'Party' },
    { value: 'Pop', label: 'Pop' },
    { value: 'Psytrance', label: 'Psytrance' },
    { value: 'R&B', label: 'R&B' },
    { value: 'Rap', label: 'Rap' },
    { value: 'Reggae', label: 'Reggae' },
    { value: 'Rock', label: 'Rock' },
    { value: 'Singer/Songwriter', label: 'Singer/Songwriter' },
    { value: 'Soundtrack', label: 'Soundtrack' },
    { value: 'Tex-Mex Tejano', label: 'Tex-Mex Tejano' },
    { value: 'Trance', label: 'Trance' },
    { value: 'World', label: 'World' },
  ],
  Film: [
    { value: 'Action', label: 'Action' },
    { value: 'Adventure', label: 'Adventure' },
    { value: 'Animation', label: 'Animation' },
    { value: 'Anime', label: 'Anime' },
    { value: 'Biopic', label: 'Biopic' },
    { value: 'Bollywood', label: 'Bollywood' },
    { value: 'British', label: 'British' },
    { value: 'Cartoon', label: 'Cartoon' },
    { value: 'Children', label: 'Children' },
    { value: 'Comedy', label: 'Comedy' },
    { value: 'Concert', label: 'Concert' },
    { value: 'Crime', label: 'Crime' },
    { value: 'Cult', label: 'Cult' },
    { value: 'Detective', label: 'Detective' },
    { value: 'Disaster', label: 'Disaster' },
    { value: 'Documentary', label: 'Documentary' },
    { value: 'Drama', label: 'Drama' },
    { value: 'Epic', label: 'Epic' },
    { value: 'Exotic', label: 'Exotic' },
    { value: 'Fantasy', label: 'Fantasy' },
    { value: 'Foreign', label: 'Foreign' },
    { value: 'Historical', label: 'Historical' },
    { value: 'Horror', label: 'Horror' },
    { value: 'Independent', label: 'Independent' },
    { value: 'Musical', label: 'Musical' },
    { value: 'Mystery', label: 'Mystery' },
    { value: 'Noir', label: 'Noir' },
    { value: 'Novella', label: 'Novella' },
    { value: 'Quiz Show', label: 'Quiz Show' },
    { value: 'Romance', label: 'Romance' },
    { value: 'Science Fiction', label: 'Science Fiction' },
    { value: 'Series', label: 'Series' },
    { value: 'Silent', label: 'Silent' },
    { value: 'Sports', label: 'Sports' },
    { value: 'Spy', label: 'Spy' },
    { value: 'Stand-Up Comedy', label: 'Stand-Up Comedy' },
    { value: 'Superhero', label: 'Superhero' },
    { value: 'Supernatural', label: 'Supernatural' },
    { value: 'Thriller', label: 'Thriller' },
    { value: 'Tv', label: 'Tv' },
    { value: 'Vampire', label: 'Vampire' },
    { value: 'War', label: 'War' },
    { value: 'Western', label: 'Western' },
    { value: 'Zombie', label: 'Zombie' },
  ],
  'Video Games': [
    { value: 'Action Role-Playing', label: 'Action Role-Playing' },
    { value: 'Action Role-Playing', label: 'Action Role-Playing' },
    { value: 'Action-Adventure', label: 'Action-Adventure' },
    { value: 'Adventure', label: 'Adventure' },
    { value: 'Arcade', label: 'Arcade' },
    { value: 'Battle Arena - Royale', label: 'Battle Arena - Royale' },
    { value: 'Board', label: 'Board' },
    { value: 'Card', label: 'Card' },
    { value: 'Casino', label: 'Casino' },
    { value: 'Casual', label: 'Casual' },
    { value: 'Children', label: 'Children' },
    { value: 'Construction', label: 'Construction' },
    { value: 'Creative', label: 'Creative' },
    { value: 'Fighting', label: 'Fighting' },
    { value: 'Horror', label: 'Horror' },
    { value: 'Learning', label: 'Learning' },
    { value: 'M.M.O.', label: 'M.M.O.' },
    { value: 'Management', label: 'Management' },
    { value: 'Mobile', label: 'Mobile' },
    { value: 'Multiplayer', label: 'Multiplayer' },
    { value: 'Online', label: 'Online' },
    { value: 'Open World', label: 'Open World' },
    { value: 'Party', label: 'Party' },
    { value: 'Pets', label: 'Pets' },
    { value: 'Puzzle', label: 'Puzzle' },
    { value: 'Racing', label: 'Racing' },
    { value: 'Real-Time Strategy', label: 'Real-Time Strategy' },
    { value: 'Sandbox', label: 'Sandbox' },
    { value: 'Shooter', label: 'Shooter' },
    { value: 'Simulation', label: 'Simulation' },
    { value: 'Strategy', label: 'Strategy' },
    { value: 'Survival', label: 'Survival' },
    { value: 'Tower Defense', label: 'Tower Defense' },
    { value: 'Trivia', label: 'Trivia' },
    { value: 'Virtual Reality', label: 'Virtual Reality' },
  ],
  'Outdoor Hobbies': [
    { value: 'Aerobatics', label: 'Aerobatics' },
    { value: 'Aeroplane flying', label: 'Aeroplane flying' },
    { value: 'Air Sphering', label: 'Air Sphering' },
    { value: 'Air rifle & pistol Shooting', label: 'Air rifle & pistol Shooting' },
    { value: 'Airsoft', label: 'Airsoft' },
    { value: 'Aquascape', label: 'Aquascape' },
    { value: 'Argo Cats', label: 'Argo Cats' },
    { value: 'Astronomy', label: 'Astronomy' },
    { value: 'BASE Jumping', label: 'BASE Jumping' },
    { value: 'Banana rides', label: 'Banana rides' },
    { value: 'Bar Hopping', label: 'Bar Hopping' },
    { value: 'Baton Twirling', label: 'Baton Twirling' },
    { value: 'Battle Reenactments', label: 'Battle Reenactments' },
    { value: 'Beach', label: 'Beach' },
    { value: 'Bicycle Polo', label: 'Bicycle Polo' },
    { value: 'Bird Watching', label: 'Bird Watching' },
    { value: 'Blackwater rafting', label: 'Blackwater rafting' },
    { value: 'Body Boarding', label: 'Body Boarding' },
    { value: 'Bouldering', label: 'Bouldering' },
    { value: 'Bowls', label: 'Bowls' },
    { value: 'Bridge Jumping', label: 'Bridge Jumping' },
    { value: 'Bungee Jumping', label: 'Bungee Jumping' },
    { value: 'Bushcraft and Survival', label: 'Bushcraft and Survival' },
    { value: 'Camel trekking', label: 'Camel trekking' },
    { value: 'Camping', label: 'Camping' },
    { value: 'Canyoning', label: 'Canyoning' },
    { value: 'Carnivals', label: 'Carnivals' },
    { value: 'Carriage Driving', label: 'Carriage Driving' },
    { value: 'Cave Diving', label: 'Cave Diving' },
    { value: 'Circus', label: 'Circus' },
    { value: 'Climbing courses', label: 'Climbing courses' },
    { value: 'Concerts', label: 'Concerts' },
    { value: 'Cookout', label: 'Cookout' },
    { value: 'Crabbing', label: 'Crabbing' },
    { value: 'Crossbow', label: 'Crossbow' },
    { value: 'Demolition Derby', label: 'Demolition Derby' },
    { value: 'Dodgeball', label: 'Dodgeball' },
    { value: 'Drones', label: 'Drones' },
    { value: 'Exercise', label: 'Exercise' },
    { value: 'Festivals', label: 'Festivals' },
    { value: 'Fishing Trips', label: 'Fishing Trips' },
    { value: 'Fitness Bootcamp', label: 'Fitness Bootcamp' },
    { value: 'Flyboard', label: 'Flyboard' },
    { value: 'Folk Dancing', label: 'Folk Dancing' },
    { value: 'Footbags', label: 'Footbags' },
    { value: 'Fruit Picking', label: 'Fruit Picking' },
    { value: 'Gardening', label: 'Gardening' },
    { value: 'Geocaching', label: 'Geocaching' },
    { value: 'Gymnastics', label: 'Gymnastics' },
    { value: 'Hang Gliding', label: 'Hang Gliding' },
    { value: 'Helicopters', label: 'Helicopters' },
    { value: 'Hiking', label: 'Hiking' },
    { value: 'Horse Riding', label: 'Horse Riding' },
    { value: 'Hot Air Balloon', label: 'Hot Air Balloon' },
    { value: 'Ice Climbing', label: 'Ice Climbing' },
    { value: 'Ice Karting', label: 'Ice Karting' },
    { value: 'Jet Skiing', label: 'Jet Skiing' },
    { value: 'Kitesurfing', label: 'Kitesurfing' },
    { value: 'Kneeboarding', label: 'Kneeboarding' },
    { value: 'Landboarding', label: 'Landboarding' },
    { value: 'Laser Tag', label: 'Laser Tag' },
    { value: 'Lawn Mowing', label: 'Lawn Mowing' },
    { value: 'Longbow', label: 'Longbow' },
    { value: 'Live Action Role Playing', label: 'Live Action Role Playing' },
    { value: 'Llama trekking', label: 'Llama trekking' },
    { value: 'Marathon Running', label: 'Marathon Running' },
    { value: 'Microlights', label: 'Microlights' },
    { value: 'Mini Golf', label: 'Mini Golf' },
    { value: 'Model Rockets', label: 'Model Rockets' },
    { value: 'Model airplanes', label: 'Model airplanes' },
    { value: 'Monster Trucks', label: 'Monster Trucks' },
    { value: 'Motor Sports', label: 'Motor Sports' },
    { value: 'Motorcycling, Motocross and dirt biking', label: 'Motorcycling, Motocross and dirt biking' },
    { value: 'Mountain Bikes', label: 'Mountain Bikes' },
    { value: 'Mountain Boarding', label: 'Mountain Boarding' },
    { value: 'Mountaineering', label: 'Mountaineering' },
    { value: 'Mud Racing', label: 'Mud Racing' },
    { value: 'Nature', label: 'Nature' },
    { value: 'Paintballing', label: 'Paintballing' },
    { value: 'Paragliding', label: 'Paragliding' },
    { value: 'Parascending', label: 'Parascending' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Pistols', label: 'Pistols' },
    { value: 'Pogo', label: 'Pogo' },
    { value: 'Pond Dipping', label: 'Pond Dipping' },
    { value: 'Quad Biking', label: 'Quad Biking' },
    { value: 'Quoits', label: 'Quoits' },
    { value: 'Raft Building', label: 'Raft Building' },
    { value: 'Rally Driving', label: 'Rally Driving' },
    { value: 'Rifles', label: 'Rifles' },
    { value: 'Remote Control Cars', label: 'Remote Control Cars' },
    { value: 'Rock Climbing', label: 'Rock Climbing' },
    { value: 'Rock Collecting', label: 'Rock Collecting' },
    { value: 'Roller Coaster', label: 'Roller Coaster' },
    { value: 'Rope Swings', label: 'Rope Swings' },
    { value: 'Rounders', label: 'Rounders' },
    { value: 'Safari', label: 'Safari' },
    { value: 'Sailing', label: 'Sailing' },
    { value: 'Sandboarding', label: 'Sandboarding' },
    { value: 'Scavenger Hunts', label: 'Scavenger Hunts' },
    { value: 'Scooter Freestyle', label: 'Scooter Freestyle' },
    { value: 'Scuba Diving', label: 'Scuba Diving' },
    { value: 'Segway Offroading', label: 'Segway Offroading' },
    { value: 'Shooting', label: 'Shooting' },
    { value: 'Shopping', label: 'Shopping' },
    { value: 'Sightseeing', label: 'Sightseeing' },
    { value: 'Skeet Shooting', label: 'Skeet Shooting' },
    { value: 'Skim Boarding', label: 'Skim Boarding' },
    { value: 'Skydiving', label: 'Skydiving' },
    { value: 'Slacklining', label: 'Slacklining' },
    { value: 'Snorkeling', label: 'Snorkeling' },
    { value: 'Snow Kiting', label: 'Snow Kiting' },
    { value: 'Snow Shoeing', label: 'Snow Shoeing' },
    { value: 'Snowmobiling', label: 'Snowmobiling' },
    { value: 'Soap Box Kart Racing', label: 'Soap Box Kart Racing' },
    { value: 'Sphering', label: 'Sphering' },
    { value: 'Stand up paddle boarding', label: 'Stand up paddle boarding' },
    { value: 'Steam Trains', label: 'Steam Trains' },
    { value: 'Stock Car Racing', label: 'Stock Car Racing' },
    { value: 'Street Improvisation', label: 'Street Improvisation' },
    { value: 'Swimming', label: 'Swimming' },
    { value: 'Swimming with dolphins', label: 'Swimming with dolphins' },
    { value: 'Tai Chi', label: 'Tai Chi' },
    { value: 'Team Building Activities', label: 'Team Building Activities' },
    { value: 'Tombstoning', label: 'Tombstoning' },
    { value: 'Tractor Pulling', label: 'Tractor Pulling' },
    { value: 'Trains', label: 'Trains' },
    { value: 'Treasure Hunting and Metal Detectors', label: 'Treasure Hunting and Metal Detectors' },
    { value: 'Treehouses', label: 'Treehouses' },
    { value: 'Vacationing', label: 'Vacationing' },
    { value: 'Walking the Dog', label: 'Walking the Dog' },
    { value: 'Washing the Car', label: 'Washing the Car' },
    { value: 'Water Fights', label: 'Water Fights' },
    { value: 'Water Jet Pack Flying', label: 'Water Jet Pack Flying' },
    { value: 'Water Parks', label: 'Water Parks' },
    { value: 'Weather', label: 'Weather' },
    { value: 'Wildlife watching', label: 'Wildlife watching' },
    { value: 'Windsurfing', label: 'Windsurfing' },
    { value: 'Yacht Charters', label: 'Yacht Charters' },
    { value: 'Yachting', label: 'Yachting' },
    { value: 'Yoga', label: 'Yoga' },
    { value: 'Zap Cat Racing', label: 'Zap Cat Racing' },
    { value: 'Zorbing', label: 'Zorbing' },
    { value: 'Zumba', label: 'Zumba' },
  ],
  'Indoor Hobbies': [
    { value: '00s Nostalgia', label: '00s Nostalgia' },
    { value: '10s Nostalgia', label: '10s Nostalgia' },
    { value: '3d Printing', label: '3d Printing' },
    { value: '60s Nostalgia', label: '60s Nostalgia' },
    { value: '70s Nostalgia', label: '70s Nostalgia' },
    { value: '80s Nostalgia', label: '80s Nostalgia' },
    { value: '90s Nostalgia', label: '90s Nostalgia' },
    { value: 'Aquariums', label: 'Aquariums' },
    { value: 'Beatboxing', label: 'Beatboxing' },
    { value: 'Binge Watching', label: 'Binge Watching' },
    { value: 'Blogging', label: 'Blogging' },
    { value: 'Board Card Games', label: 'Board Card Games' },
    { value: 'Breakfast', label: 'Breakfast' },
    { value: 'Building Furniture', label: 'Building Furniture' },
    { value: 'Calligraphy', label: 'Calligraphy' },
    { value: 'Candle Making', label: 'Candle Making' },
    { value: 'Ceramics', label: 'Ceramics' },
    { value: 'Chess', label: 'Chess' },
    { value: 'Chilling', label: 'Chilling' },
    { value: 'Cleaning', label: 'Cleaning' },
    { value: 'Coding', label: 'Coding' },
    { value: 'Coffee', label: 'Coffee' },
    { value: 'Coloring', label: 'Coloring' },
    { value: 'Comics', label: 'Comics' },
    { value: 'Computer Programming', label: 'Computer Programming' },
    { value: 'Cooking', label: 'Cooking' },
    { value: 'Cosplaying', label: 'Cosplaying' },
    { value: 'Crocheting', label: 'Crocheting' },
    { value: 'Cryptography', label: 'Cryptography' },
    { value: 'Crystals', label: 'Crystals' },
    { value: 'Cultures', label: 'Cultures' },
    { value: 'Dance', label: 'Dance' },
    { value: 'Decorating', label: 'Decorating' },
    { value: 'Dinner', label: 'Dinner' },
    { value: 'Diorama', label: 'Diorama' },
    { value: 'Diy', label: 'Diy' },
    { value: 'Drama', label: 'Drama' },
    { value: 'Drumming', label: 'Drumming' },
    { value: 'Embroidery', label: 'Embroidery' },
    { value: 'Electronics', label: 'Electronics' },
    { value: 'Fashion', label: 'Fashion' },
    { value: 'Figurines', label: 'Figurines' },
    { value: 'Gambling', label: 'Gambling' },
    { value: 'Game Developing', label: 'Game Developing' },
    { value: 'Genealogy', label: 'Genealogy' },
    { value: 'Glassblowing', label: 'Glassblowing' },
    { value: 'Go', label: 'Go' },
    { value: 'Grooming', label: 'Grooming' },
    { value: 'Guitar', label: 'Guitar' },
    { value: 'Gunsmithing', label: 'Gunsmithing' },
    { value: 'Home Improvement', label: 'Home Improvement' },
    { value: 'Homebrewing', label: 'Homebrewing' },
    { value: 'Hosting', label: 'Hosting' },
    { value: 'Iceskating', label: 'Iceskating' },
    { value: 'Jewelry Making', label: 'Jewelry Making' },
    { value: 'Jigsaw Puzzles', label: 'Jigsaw Puzzles' },
    { value: 'Jokes', label: 'Jokes' },
    { value: 'Juggling', label: 'Juggling' },
    { value: 'Keyboards', label: 'Keyboards' },
    { value: 'Knapping', label: 'Knapping' },
    { value: 'Knife Making', label: 'Knife Making' },
    { value: 'Knitting', label: 'Knitting' },
    { value: 'Lacemaking', label: 'Lacemaking' },
    { value: 'Lapidary', label: 'Lapidary' },
    { value: 'Learning Facts', label: 'Learning Facts' },
    { value: 'Leather Crafting', label: 'Leather Crafting' },
    { value: 'Listening To Music', label: 'Listening To Music' },
    { value: 'Livestreaming', label: 'Livestreaming' },
    { value: 'Lunch', label: 'Lunch' },
    { value: 'Macrame', label: 'Macrame' },
    { value: 'Marching Band', label: 'Marching Band' },
    { value: 'Miniatures', label: 'Miniatures' },
    { value: 'Model Making', label: 'Model Making' },
    { value: 'Movie Night', label: 'Movie Night' },
    { value: 'Origami', label: 'Origami' },
    { value: 'Personal Reflection', label: 'Personal Reflection' },
    { value: 'Philately', label: 'Philately' },
    { value: 'Piano', label: 'Piano' },
    { value: 'Podcasts', label: 'Podcasts' },
    { value: 'Poi', label: 'Poi' },
    { value: 'Poker', label: 'Poker' },
    { value: 'Pottery', label: 'Pottery' },
    { value: 'Proverbs', label: 'Proverbs' },
    { value: 'Puppetry', label: 'Puppetry' },
    { value: 'Puzzle Game', label: 'Puzzle Game' },
    { value: 'Pyrography', label: 'Pyrography' },
    { value: 'Quilting', label: 'Quilting' },
    { value: 'Recipies', label: 'Recipies' },
    { value: 'Scrapbooking', label: 'Scrapbooking' },
    { value: 'Security', label: 'Security' },
    { value: 'Sewing', label: 'Sewing' },
    { value: 'Singing', label: 'Singing' },
    { value: 'Soapmaking', label: 'Soapmaking' },
    { value: 'Sudoku', label: 'Sudoku' },
    { value: 'Synthesizer', label: 'Synthesizer' },
    { value: 'Tabletop Games', label: 'Tabletop Games' },
    { value: 'Taxidermy', label: 'Taxidermy' },
    { value: 'Theraputics', label: 'Theraputics' },
    { value: 'Trivia', label: 'Trivia' },
    { value: 'Video Creationg', label: 'Video Creationg' },
    { value: 'Video Editing', label: 'Video Editing' },
    { value: 'Watching Television', label: 'Watching Television' },
    { value: 'Whittling', label: 'Whittling' },
    { value: 'Wood Carving', label: 'Wood Carving' },
    { value: 'Woodworking', label: 'Woodworking' },
    { value: 'Worldbuilding', label: 'Worldbuilding' },
    { value: 'Writing', label: 'Writing' },
  ],
  'Favourite Animals': [
    { value: 'Aardvark', label: 'Aardvark' },
    { value: 'Alligator', label: 'Alligator' },
    { value: 'Alpaca', label: 'Alpaca' },
    { value: 'Anaconda', label: 'Anaconda' },
    { value: 'Ant', label: 'Ant' },
    { value: 'Antelope', label: 'Antelope' },
    { value: 'Ape', label: 'Ape' },
    { value: 'Aphid', label: 'Aphid' },
    { value: 'Armadillo', label: 'Armadillo' },
    { value: 'Asp', label: 'Asp' },
    { value: 'Ass', label: 'Ass' },
    { value: 'Baboon', label: 'Baboon' },
    { value: 'Badger', label: 'Badger' },
    { value: 'Bald Eagle', label: 'Bald Eagle' },
    { value: 'Barracuda', label: 'Barracuda' },
    { value: 'Bass', label: 'Bass' },
    { value: 'Basset Hound', label: 'Basset Hound' },
    { value: 'Bat', label: 'Bat' },
    { value: 'Bearded Dragon', label: 'Bearded Dragon' },
    { value: 'Beaver', label: 'Beaver' },
    { value: 'Bedbug', label: 'Bedbug' },
    { value: 'Bee', label: 'Bee' },
    { value: 'Beetle', label: 'Beetle' },
    { value: 'Bird', label: 'Bird' },
    { value: 'Bison', label: 'Bison' },
    { value: 'Black panther', label: 'Black panther' },
    { value: 'Black Widow Spider', label: 'Black Widow Spider' },
    { value: 'Blue Jay', label: 'Blue Jay' },
    { value: 'Blue Whale', label: 'Blue Whale' },
    { value: 'Bobcat', label: 'Bobcat' },
    { value: 'Buffalo', label: 'Buffalo' },
    { value: 'Butterfly', label: 'Butterfly' },
    { value: 'Buzzard', label: 'Buzzard' },
    { value: 'Camel', label: 'Camel' },
    { value: 'Caribou', label: 'Caribou' },
    { value: 'Carp', label: 'Carp' },
    { value: 'Cat', label: 'Cat' },
    { value: 'Caterpillar', label: 'Caterpillar' },
    { value: 'Catfish', label: 'Catfish' },
    { value: 'Cheetah', label: 'Cheetah' },
    { value: 'Chicken', label: 'Chicken' },
    { value: 'Chimpanzee', label: 'Chimpanzee' },
    { value: 'Chipmunk', label: 'Chipmunk' },
    { value: 'Cobra', label: 'Cobra' },
    { value: 'Cod', label: 'Cod' },
    { value: 'Condor', label: 'Condor' },
    { value: 'Cougar', label: 'Cougar' },
    { value: 'Cow', label: 'Cow' },
    { value: 'Coyote', label: 'Coyote' },
    { value: 'Crab', label: 'Crab' },
    { value: 'Crane', label: 'Crane' },
    { value: 'Cricket', label: 'Cricket' },
    { value: 'Crocodile', label: 'Crocodile' },
    { value: 'Crow', label: 'Crow' },
    { value: 'Cuckoo', label: 'Cuckoo' },
    { value: 'Deer', label: 'Deer' },
    { value: 'Dinosaur', label: 'Dinosaur' },
    { value: 'Dog', label: 'Dog' },
    { value: 'Dolphin', label: 'Dolphin' },
    { value: 'Donkey', label: 'Donkey' },
    { value: 'Dove', label: 'Dove' },
    { value: 'Dragonfly', label: 'Dragonfly' },
    { value: 'Duck', label: 'Duck' },
    { value: 'Eagle', label: 'Eagle' },
    { value: 'Eel', label: 'Eel' },
    { value: 'Elephant', label: 'Elephant' },
    { value: 'Emu', label: 'Emu' },
    { value: 'Falcon', label: 'Falcon' },
    { value: 'Ferret', label: 'Ferret' },
    { value: 'Finch', label: 'Finch' },
    { value: 'Fish', label: 'Fish' },
    { value: 'Flamingo', label: 'Flamingo' },
    { value: 'Flea', label: 'Flea' },
    { value: 'Fly', label: 'Fly' },
    { value: 'Fox', label: 'Fox' },
    { value: 'Frog', label: 'Frog' },
    { value: 'Goat', label: 'Goat' },
    { value: 'Goose', label: 'Goose' },
    { value: 'Gopher', label: 'Gopher' },
    { value: 'Gorilla', label: 'Gorilla' },
    { value: 'Grasshopper', label: 'Grasshopper' },
    { value: 'Hamster', label: 'Hamster' },
    { value: 'Hare', label: 'Hare' },
    { value: 'Hawk', label: 'Hawk' },
    { value: 'Hippopotamus', label: 'Hippopotamus' },
    { value: 'Horse', label: 'Horse' },
    { value: 'Hummingbird', label: 'Hummingbird' },
    { value: 'Humpback Whale', label: 'Humpback Whale' },
    { value: 'Husky', label: 'Husky' },
    { value: 'Iguana', label: 'Iguana' },
    { value: 'Impala', label: 'Impala' },
    { value: 'Kangaroo', label: 'Kangaroo' },
    { value: 'Lemur', label: 'Lemur' },
    { value: 'Leopard', label: 'Leopard' },
    { value: 'Lion', label: 'Lion' },
    { value: 'Lizard', label: 'Lizard' },
    { value: 'Llama', label: 'Llama' },
    { value: 'Lobster', label: 'Lobster' },
    { value: 'Marmot', label: 'Marmot' },
    { value: 'Monitor lizard', label: 'Monitor lizard' },
    { value: 'Monkey', label: 'Monkey' },
    { value: 'Moose', label: 'Moose' },
    { value: 'Mosquito', label: 'Mosquito' },
    { value: 'Moth', label: 'Moth' },
    { value: 'Mountain goat', label: 'Mountain goat' },
    { value: 'Mouse', label: 'Mouse' },
    { value: 'Mule', label: 'Mule' },
    { value: 'Octopus', label: 'Octopus' },
    { value: 'Orca', label: 'Orca' },
    { value: 'Ostrich', label: 'Ostrich' },
    { value: 'Otter', label: 'Otter' },
    { value: 'Owl', label: 'Owl' },
    { value: 'Ox', label: 'Ox' },
    { value: 'Oyster', label: 'Oyster' },
    { value: 'Panda', label: 'Panda' },
    { value: 'Parrot', label: 'Parrot' },
    { value: 'Peacock', label: 'Peacock' },
    { value: 'Pelican', label: 'Pelican' },
    { value: 'Penguin', label: 'Penguin' },
    { value: 'Perch', label: 'Perch' },
    { value: 'Pheasant', label: 'Pheasant' },
    { value: 'Pig', label: 'Pig' },
    { value: 'Pigeon', label: 'Pigeon' },
    { value: 'Polar bear', label: 'Polar bear' },
    { value: 'Porcupine', label: 'Porcupine' },
    { value: 'Quoll', label: 'Quoll' },
    { value: 'Rabbit', label: 'Rabbit' },
    { value: 'Raccoon', label: 'Raccoon' },
    { value: 'Rat', label: 'Rat' },
    { value: 'Rattlesnake', label: 'Rattlesnake' },
    { value: 'Red Panda', label: 'Red Panda' },
    { value: 'Rooster', label: 'Rooster' },
    { value: 'Sea lion', label: 'Sea lion' },
    { value: 'Sheep', label: 'Sheep' },
    { value: 'Shrew', label: 'Shrew' },
    { value: 'Sloth', label: 'Sloth' },
    { value: 'Snail', label: 'Snail' },
    { value: 'Snake', label: 'Snake' },
    { value: 'Spider', label: 'Spider' },
    { value: 'Tiger', label: 'Tiger' },
    { value: 'Turkey', label: 'Turkey' },
    { value: 'Wolf', label: 'Wolf' },
    { value: 'Wombat', label: 'Wombat' },
    { value: 'Zebra', label: 'Zebra' },
  ],
  Supernatural: [
    { value: 'Alchemy', label: 'Alchemy' },
    { value: 'Astrology', label: 'Astrology' },
    { value: 'Chi', label: 'Chi' },
    { value: 'Divination', label: 'Divination' },
    { value: 'Energy', label: 'Energy' },
    { value: 'Extraterrestrial', label: 'Extraterrestrial' },
    { value: 'Hermeticism', label: 'Hermeticism' },
    { value: 'Illusion', label: 'Illusion' },
    { value: 'Magic', label: 'Magic' },
    { value: 'Medicine', label: 'Medicine' },
    { value: 'Necromancy', label: 'Necromancy' },
    { value: 'Paranormal', label: 'Paranormal' },
    { value: 'Reiki', label: 'Reiki' },
    { value: 'Sorcery', label: 'Sorcery' },
    { value: 'Spiritual Healing', label: 'Spiritual Healing' },
  ],
  Toys: [
    { value: 'Action Figures', label: 'Action Figures' },
    { value: 'Animal', label: 'Animal' },
    { value: 'App Controlled', label: 'App Controlled' },
    { value: 'Balance Bikes', label: 'Balance Bikes' },
    { value: 'Ball Pits', label: 'Ball Pits' },
    { value: 'Balloons', label: 'Balloons' },
    { value: 'Balls', label: 'Balls' },
    { value: 'Bath', label: 'Bath' },
    { value: 'Beach', label: 'Beach' },
    { value: 'Bean Bags', label: 'Bean Bags' },
    { value: 'Bicycles', label: 'Bicycles' },
    { value: 'Binoculars', label: 'Binoculars' },
    { value: 'Board Games', label: 'Board Games' },
    { value: 'Boats', label: 'Boats' },
    { value: 'Brain Teasers', label: 'Brain Teasers' },
    { value: 'Bubbles', label: 'Bubbles' },
    { value: 'Building Sets', label: 'Building Sets' },
    { value: 'Card Games', label: 'Card Games' },
    { value: 'Cars', label: 'Cars' },
    { value: 'Cash Registers', label: 'Cash Registers' },
    { value: 'Clay & Dough', label: 'Clay & Dough' },
    { value: 'Coding Kits', label: 'Coding Kits' },
    { value: 'Coins & Stamps', label: 'Coins & Stamps' },
    { value: 'Collectible Card Games', label: 'Collectible Card Games' },
    { value: 'Construction Construction Vehicles', label: 'Construction Construction Vehicles' },
    { value: 'Costume Jewellery', label: 'Costume Jewellery' },
    { value: 'Craft Supplies', label: 'Craft Supplies' },
    { value: 'Creative', label: 'Creative' },
    { value: 'Dance', label: 'Dance' },
    { value: 'Dart Guns', label: 'Dart Guns' },
    { value: 'Detective & Spy', label: 'Detective & Spy' },
    { value: 'Doll Accessories', label: 'Doll Accessories' },
    { value: 'Dollhouses', label: 'Dollhouses' },
    { value: 'Dolls', label: 'Dolls' },
    { value: 'Drawing Supplies', label: 'Drawing Supplies' },
    { value: 'Dress Up & Pretend Play', label: 'Dress Up & Pretend Play' },
    { value: 'Educational Electronics', label: 'Educational Electronics' },
    { value: 'Electronic Pets', label: 'Electronic Pets' },
    { value: 'Exploration', label: 'Exploration' },
    { value: 'Fishing', label: 'Fishing' },
    { value: 'Flying', label: 'Flying' },
    { value: 'Fortune Telling', label: 'Fortune Telling' },
    { value: 'Gags & Practical Jokes', label: 'Gags & Practical Jokes' },
    { value: 'Globes', label: 'Globes' },
    { value: 'Hoppers', label: 'Hoppers' },
    { value: 'Housekeeping', label: 'Housekeeping' },
    { value: 'Interactive Plush', label: 'Interactive Plush' },
    { value: 'Jump Rope', label: 'Jump Rope' },
    { value: 'Kitchen', label: 'Kitchen' },
    { value: 'Kites', label: 'Kites' },
    { value: 'Magic Kits', label: 'Magic Kits' },
    { value: 'Magnetic', label: 'Magnetic' },
    { value: 'Marbles', label: 'Marbles' },
    { value: 'Media Players', label: 'Media Players' },
    { value: 'Medical Kits', label: 'Medical Kits' },
    { value: 'Microscopes', label: 'Microscopes' },
    { value: 'Models', label: 'Models' },
    { value: 'Money Banks', label: 'Money Banks' },
    { value: 'Musical Instruments', label: 'Musical Instruments' },
    { value: 'Musical', label: 'Musical' },
    { value: 'Painting Supplies', label: 'Painting Supplies' },
    { value: 'Perpetual Motion & Marble Runs', label: 'Perpetual Motion & Marble Runs' },
    { value: 'Play Money', label: 'Play Money' },
    { value: 'Play Tools', label: 'Play Tools' },
    { value: 'Play Vehicles', label: 'Play Vehicles' },
    { value: 'Playground Equipment', label: 'Playground Equipment' },
    { value: 'Playhouses', label: 'Playhouses' },
    { value: 'Pogo Sticks', label: 'Pogo Sticks' },
    { value: 'Preschool Toys', label: 'Preschool Toys' },
    { value: 'Pretend Electronics', label: 'Pretend Electronics' },
    { value: 'Prisms & Kaleidoscopes', label: 'Prisms & Kaleidoscopes' },
    { value: 'Programmable', label: 'Programmable' },
    { value: 'Puppets', label: 'Puppets' },
    { value: 'Puzzles', label: 'Puzzles' },
    { value: 'Radio Controlled', label: 'Radio Controlled' },
    { value: 'Robots', label: 'Robots' },
    { value: 'Rockets', label: 'Rockets' },
    { value: 'Rollerblades', label: 'Rollerblades' },
    { value: 'Rollerskates', label: 'Rollerskates' },
    { value: 'STEM Toys', label: 'STEM Toys' },
    { value: 'Sandboxes', label: 'Sandboxes' },
    { value: 'Science Kits', label: 'Science Kits' },
    { value: 'Scooters', label: 'Scooters' },
    { value: 'Shopping Carts', label: 'Shopping Carts' },
    { value: 'Skateboards', label: 'Skateboards' },
    { value: 'Skates', label: 'Skates' },
    { value: 'Slime & Putty', label: 'Slime & Putty' },
    { value: 'Space Toys', label: 'Space Toys' },
    { value: 'Spinning Tops', label: 'Spinning Tops' },
    { value: 'Sporting Equipment', label: 'Sporting Equipment' },
    { value: 'Stacking Blocks', label: 'Stacking Blocks' },
    { value: 'Stickers', label: 'Stickers' },
    { value: 'Stuffed Animals', label: 'Stuffed Animals' },
    { value: 'Telescopes', label: 'Telescopes' },
    { value: 'Tent', label: 'Tent' },
    { value: 'Traditional', label: 'Traditional' },
    { value: 'Train Sets', label: 'Train Sets' },
    { value: 'Trampolines', label: 'Trampolines' },
    { value: 'Tricycles', label: 'Tricycles' },
    { value: 'Tunnel', label: 'Tunnel' },
    { value: 'Video Games', label: 'Video Games' },
    { value: 'Wagons', label: 'Wagons' },
    { value: 'Walkie Talkies', label: 'Walkie Talkies' },
    { value: 'Water', label: 'Water' },
    { value: 'Water Tables', label: 'Water Tables' },
    { value: 'Wooden', label: 'Wooden' },
    { value: 'Yo-yo', label: 'Yo-yo' },
  ],
};
